In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am good boy',
      'i am good developer',
      'understand the meaning of words',
      'your videos are good',
      'i like your content',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'i am good developer',
 'understand the meaning of words',
 'your videos are good',
 'i like your content']

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[28, 138, 7456, 960],
 [28, 138, 7456, 4230],
 [28, 1395, 7456, 9642],
 [1213, 3909, 1934, 4551],
 [1213, 3909, 1934, 4148],
 [6706, 28, 4722, 7456, 5553],
 [6278, 7033, 2249, 1934],
 [1213, 3171, 6278, 3845]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [22]:
sent_len=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0   28  138 7456  960]
 [   0    0    0    0   28  138 7456 4230]
 [   0    0    0    0   28 1395 7456 9642]
 [   0    0    0    0 1213 3909 1934 4551]
 [   0    0    0    0 1213 3909 1934 4148]
 [   0    0    0 6706   28 4722 7456 5553]
 [   0    0    0    0 6278 7033 2249 1934]
 [   0    0    0    0 1213 3171 6278 3845]]


In [23]:
dim=10

In [28]:

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')


c:\Users\IT Tech\OneDrive\Documents\GenAI\ANN_project\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [29]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 685ms/step


array([[[-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.03159197, -0.04884158,  0.00341012, -0.04564166,
          0.03476015,  0.00634172,  0.00646175, -0.03327105,
         -0.00041612, -0.0155654 ],
        [-0.02873324,  0.03691586,  0.01381056,  0.01704583,
         -0.00078007, -0.02684796,  0.02057424, -0.00377221,
          0.02491376, -0.01434833],
        [-0.01247441,  0.02856903,  0.04781851, -0.0

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0,   28,  138, 7456,  960])

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step


array([[[-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.04057596,  0.04654938, -0.00379999,  0.03109702,
          0.02268815, -0.02050941,  0.00109534,  0.02295912,
          0.00055997,  0.04460514],
        [-0.03159197, -0.04884158,  0.00341012, -0.04564166,
          0.03476015,  0.00634172,  0.00646175, -0.03327105,
         -0.00041612, -0.0155654 ],
        [-0.02873324,  0.03691586,  0.01381056,  0.01704583,
         -0.00078007, -0.02684796,  0.02057424, -0.00377221,
          0.02491376, -0.01434833],
        [-0.01247441,  0.02856903,  0.04781851, -0.0